/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Client.Patient;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.io.IOException;
import java.io.InputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.OutputStream;
import java.net.Socket;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import ui.menu;

/**
 *
 * @author loredanaabalo
 */
public class SignUp extends javax.swing.JFrame implements WindowListener {

    public ClientMenu menu;
    private SocketOb db;
    private SignUp signup;
    public Welcome wel;
    Boolean[] validated;
    static Boolean[] correct = {true, true, true, true, true, true, true, true, true};
    String verifiedName, verifiedLastname, verifiedPhone, verifiedEmail, verifiedMAC, verifiedDob, verifiedUsername, verifiedPassword, validationMessage;

    Patient patient = new Patient(null, null, null, null, null, null, null, null, null);

    /**
     * Creates new form U_Interface
     *
     * @param db
     */
    public SignUp(SocketOb db) {
        this.db = db;
        initComponents();
    }

    public SignUp() {
    }

    public void setSingup(SignUp singup) {
        this.signup = singup;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nametxt = new javax.swing.JTextField();
        lastnametxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        emailtxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        malecheck = new javax.swing.JCheckBox();
        femalecheck = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        phonetxt = new javax.swing.JTextField();
        dobtxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        passwordfield = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        usernametxt = new javax.swing.JTextField();
        saveNewInfoButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        goBack = new javax.swing.JButton();
        MACtxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "User Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font(".SF NS Text", 1, 12))); // NOI18N

        jLabel1.setFont(new java.awt.Font(".SF NS Text", 1, 12)); // NOI18N
        jLabel1.setText("Name:");

        jLabel2.setFont(new java.awt.Font(".SF NS Text", 1, 12)); // NOI18N
        jLabel2.setText("Last Name:");

        nametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nametxtActionPerformed(evt);
            }
        });

        lastnametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastnametxtActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font(".SF NS Text", 1, 12)); // NOI18N
        jLabel3.setText("Email:");

        jLabel4.setFont(new java.awt.Font(".SF NS Text", 1, 12)); // NOI18N
        jLabel4.setText("Gender:");

        genderGroup.add(malecheck);
        malecheck.setText("Male");
        malecheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                malecheckActionPerformed(evt);
            }
        });

        genderGroup.add(femalecheck);
        femalecheck.setText("Female");
        femalecheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femalecheckActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font(".SF NS Text", 1, 12)); // NOI18N
        jLabel7.setText("Date of Birth");

        jLabel8.setFont(new java.awt.Font(".SF NS Text", 1, 12)); // NOI18N
        jLabel8.setText("Phone Number");

        phonetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phonetxtActionPerformed(evt);
            }
        });

        dobtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dobtxtActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font(".SF NS Text", 0, 10)); // NOI18N
        jLabel9.setText("dd/mm/yyyy");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nametxt, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(lastnametxt)
                    .addComponent(emailtxt, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(phonetxt))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(malecheck)
                            .addComponent(femalecheck)
                            .addComponent(dobtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(108, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addGap(127, 127, 127))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(dobtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(malecheck))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(femalecheck)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 9, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(19, 19, 19))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lastnametxt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(emailtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phonetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27))))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Usermane and Password", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font(".SF NS Text", 1, 12))); // NOI18N

        passwordfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordfieldActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font(".SF NS Text", 1, 12)); // NOI18N
        jLabel5.setText("Password:");

        jLabel6.setFont(new java.awt.Font(".SF NS Text", 1, 12)); // NOI18N
        jLabel6.setText("Username");

        saveNewInfoButton.setBackground(new java.awt.Color(102, 153, 0));
        saveNewInfoButton.setFont(new java.awt.Font(".SF NS Text", 1, 14)); // NOI18N
        saveNewInfoButton.setForeground(new java.awt.Color(255, 255, 255));
        saveNewInfoButton.setText("Accept");
        saveNewInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveNewInfoButtonActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font(".SF NS Text", 1, 12)); // NOI18N
        jLabel10.setText("MAC address");

        goBack.setFont(new java.awt.Font(".SF NS Text", 1, 12)); // NOI18N
        goBack.setText("Go back");
        goBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(passwordfield)
                    .addComponent(usernametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(90, 90, 90)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MACtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addComponent(saveNewInfoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(goBack)
                .addGap(17, 17, 17))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(usernametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel10)
                            .addComponent(MACtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(passwordfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                        .addComponent(saveNewInfoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(goBack)))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void malecheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_malecheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_malecheckActionPerformed

    private void femalecheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femalecheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femalecheckActionPerformed

    private void passwordfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordfieldActionPerformed

    private void saveNewInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveNewInfoButtonActionPerformed

        verifiedName = nametxt.getText();
        verifiedLastname = lastnametxt.getText();
        verifiedPhone = phonetxt.getText();
        verifiedEmail = emailtxt.getText();
        verifiedMAC = MACtxt.getText();
        verifiedDob = dobtxt.getText();
        verifiedUsername = usernametxt.getText();
        verifiedPassword = new String(passwordfield.getPassword());
        validated = Validation(verifiedName, verifiedLastname, verifiedPhone, verifiedEmail, verifiedMAC, verifiedDob,
                verifiedUsername, verifiedPassword, malecheck, femalecheck);
        System.out.println(Arrays.toString(validated));
        if (Arrays.equals(validated, correct) == false) {
            validationMessage = "";
            if (validated[0] == false) {
                validationMessage = validationMessage + "The Name is not valid\n";
            }
            if (validated[1] == false) {
                validationMessage = validationMessage + "The Last Name is not valid\n";
            }
            if (validated[2] == false) {
                validationMessage = validationMessage + "The Phone is not valid\n";
            }
            if (validated[3] == false) {
                validationMessage = validationMessage + "The Email is not valid\n";
            }
            if (validated[4] == false) {
                validationMessage = validationMessage + "The MAC address is not valid\n";
            }
            if (validated[5] == false) {
                validationMessage = validationMessage + "The Date of Birth is not valid\n";
            }
            if (validated[6] == false) {
                validationMessage = validationMessage + "The Username is not valid\n";
            }
            if (validated[7] == false) {
                validationMessage = validationMessage + "The Password is not valid\n";
            }
            if (validated[8] == false) {
                validationMessage = validationMessage + "The Gender is not selected\n";
            }
            JOptionPane.showMessageDialog(null, validationMessage);
        } else {
            patient.setName(verifiedName);
            System.out.println("Name: " + patient.getName());
            patient.setLastname(verifiedLastname);
            System.out.println("Lastname: " + patient.getLastname());
            patient.setPhone(verifiedPhone);
            System.out.println("Phone: " + patient.getPhone());
            patient.setEmail(verifiedEmail);
            System.out.println("Address: " + patient.getEmail());
            patient.setMAC(verifiedMAC);
            System.out.println("MAC:" + patient.getMAC());
            if (malecheck.isSelected()) {
                patient.setGender("M");
            }
            if (femalecheck.isSelected()) {
                patient.setGender("F");
            }
            System.out.println("Gender:" + patient.getGender());
            patient.setDob(verifiedDob);
            System.out.println("Date of Birth: " + patient.getDob());
            patient.setUsername(verifiedUsername);
            System.out.println("Username:" + patient.getUsername());
            patient.setPassword(verifiedPassword);
            System.out.println("Password:" + patient.getPassword());

            if (patient.getGender() != null) {
                JOptionPane.showMessageDialog(null, "Signup was successful");
            }

            menu = new ClientMenu(db);
            menu.setClimen(menu);
            try {
                db.getOutputStream().write(0);
                db.getObjectOutputStream().writeObject(patient);
                Patient patient1 = (Patient) (db.getObjectInputStream().readObject());
                menu.setPatient(patient1);
                System.out.println(patient1);
            } catch (ClassNotFoundException | IOException ex) {
                Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex);
            }
            menu.setVisible(true);
            this.signup.setVisible(false);
        }
    }//GEN-LAST:event_saveNewInfoButtonActionPerformed

    public Patient getNewUser(Patient patient) {
        return patient;
    }
    private void nametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nametxtActionPerformed


    }//GEN-LAST:event_nametxtActionPerformed

    private void lastnametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastnametxtActionPerformed

    }//GEN-LAST:event_lastnametxtActionPerformed

    private void phonetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phonetxtActionPerformed


    }//GEN-LAST:event_phonetxtActionPerformed

    private void dobtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dobtxtActionPerformed
        //problemas con convertir un long en Date
    }//GEN-LAST:event_dobtxtActionPerformed

    private void goBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBackActionPerformed
        wel = new Welcome(db);
        wel.setWel(wel);
        wel.setVisible(true);
        this.signup.setVisible(false);
        int option = 1;
        try {
            db.getOutputStream().write(option);
        } catch (IOException ex) {
            Logger.getLogger(Welcome.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_goBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    private static void releaseResources(ObjectInputStream objectInputStream, ObjectOutputStream objectOutputStream, Socket socket,
            InputStream inputStream, OutputStream outputStream) {
        try {
            objectInputStream.close();
        } catch (IOException ex) {
            Logger.getLogger(menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            objectOutputStream.close();
        } catch (IOException ex) {
            Logger.getLogger(menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            socket.close();
        } catch (IOException ex) {
            Logger.getLogger(menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            outputStream.close();
        } catch (IOException ex) {
            Logger.getLogger(menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            inputStream.close();
        } catch (IOException ex) {
            Logger.getLogger(menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public static Boolean[] Validation(String name, String lastname, String phone, String email, String MAC, String dob, String username, String password, JCheckBox malecheck, JCheckBox femalecheck) {
        String namePattern = "[ A-Za-zñ]+";
        String phonePattern = "[6789]\\d{8}";
        String emailPattern = "([.0-9_a-z]{6,30})@(\\p{Lower}+)\\x2E(\\p{Lower}+)";
        String MACPattern = "[0-9A-F]{2}:[0-9A-F]{2}:[0-9A-F]{2}:[0-9A-F]{2}:[0-9A-F]{2}:[0-9A-F]{2}";
        String dobPattern = "\\d{4}-"
                + "((02-(0[1-9]||1\\d||2[0-8]))||"
                + "((0[13578]||1[02])-(0[1-9]||1\\d||2\\d||3[0-1]))||"
                + "((0[469]||11)-(0[1-9]||1\\d||2\\d||30)))";
        String usernamePattern = "[.0-9_a-z]{6,30}";
        String passwordPattern1 = "[\\d\\p{Alnum}\\p{Punct}]*\\d[\\d\\p{Alnum}\\p{Punct}]*";
        String passwordPattern2 = "[\\d\\p{Alnum}\\p{Punct}]*\\p{Upper}[\\d\\p{Alnum}\\p{Punct}]*";
        String passwordPattern3 = "[\\d\\p{Alnum}\\p{Punct}]*\\p{Lower}[\\d\\p{Alnum}\\p{Punct}]*";
        String passwordPattern4 = "[\\d\\p{Alnum}\\p{Punct}]*\\p{Punct}[\\d\\p{Alnum}\\p{Punct}]*";
        String passwordPattern5 = "[\\d\\p{Alnum}\\p{Punct}]{8,}";
        Boolean[] validated = new Boolean[9];
        if (name.matches(namePattern)) {
            Arrays.fill(validated, 0, 1, true);
        } else {
            Arrays.fill(validated, 0, 1, false);
        }
        if (lastname.matches(namePattern)) {
            Arrays.fill(validated, 1, 2, true);
        } else {
            Arrays.fill(validated, 1, 2, false);
        }
        if (phone.matches(phonePattern)) {
            Arrays.fill(validated, 2, 3, true);
        } else {
            Arrays.fill(validated, 2, 3, false);
        }
        if (email.matches(emailPattern)) {
            Arrays.fill(validated, 3, 4, true);
        } else {
            Arrays.fill(validated, 3, 4, false);
        }
        if (MAC.matches(MACPattern)) {
            Arrays.fill(validated, 4, 5, true);
        } else {
            Arrays.fill(validated, 4, 5, false);
        }
        if (dob.matches(dobPattern)) {
            Arrays.fill(validated, 5, 6, true);
        } else {
            Arrays.fill(validated, 5, 6, false);
        }
        if (username.matches(usernamePattern)) {
            Arrays.fill(validated, 6, 7, true);
        } else {
            Arrays.fill(validated, 6, 7, false);
        }
        if (password.matches(passwordPattern1)
                && password.matches(passwordPattern2)
                && password.matches(passwordPattern3)
                && password.matches(passwordPattern4)
                && password.matches(passwordPattern5)) {
            Arrays.fill(validated, 7, 8, true);
        } else {
            Arrays.fill(validated, 7, 8, false);
        }
        if (malecheck.isSelected() || femalecheck.isSelected()) {
            Arrays.fill(validated, 8, 9, true);
        } else {
            Arrays.fill(validated, 8, 9, false);
        }
        return validated;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField MACtxt;
    private javax.swing.JTextField dobtxt;
    private javax.swing.JTextField emailtxt;
    private javax.swing.JCheckBox femalecheck;
    private javax.swing.ButtonGroup genderGroup;
    private javax.swing.JButton goBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField lastnametxt;
    private javax.swing.JCheckBox malecheck;
    private javax.swing.JTextField nametxt;
    private javax.swing.JPasswordField passwordfield;
    private javax.swing.JTextField phonetxt;
    private javax.swing.JButton saveNewInfoButton;
    private javax.swing.JTextField usernametxt;
    // End of variables declaration//GEN-END:variables

    @Override
    public void windowOpened(WindowEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void windowClosing(WindowEvent e) {
        releaseResources(db.getObjectInputStream(), db.getObjectOutputStream(), db.getSocket(),
                db.getInputStream(), db.getOutputStream());
    }

    @Override
    public void windowClosed(WindowEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void windowIconified(WindowEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void windowDeiconified(WindowEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void windowActivated(WindowEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void windowDeactivated(WindowEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
